-- CreateEnum
CREATE TYPE "ROLE" AS ENUM ('ADMIN', 'SUPER_ADMIN', 'USER', 'MODERATOR');

-- AlterTable
ALTER TABLE "Category" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Products" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
